corelm: ar_delay
corelm_conf:
    share_emb: false
    qk_norm: true
    att_unit: 512
    head: 8
    layer: 24

# Dataloader
batch_type: numel
batch_bins: 16000
num_iters_per_epoch: 5000
accum_grad: 1
grad_clip: 5
max_epoch: 50
num_workers: 8
drop_last_iter: true
log_interval: 1000

# Criterion & Optimization
optim: adamw
optim_conf:
    lr: 0.001
    betas:
        - 0.9
        - 0.95
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5
nbest_averaging_interval: 5

# for nq setup
codec_token_per_frame: 1
codec_token_in_use: 1


# Global settings
use_amp: true
use_tf32: false
use_fsdp: false
encoder_decoder_format: false
