use_deepspeed: true
deepspeed_config: conf/tts_pretrain/deepspeed_ddp.json
deepspeed_step_sync: false

# Model
corelm: ar_delay
corelm_conf:
    share_emb: false
    att_unit: 960
    n_ctx: 4096
    hf_model_tag: HuggingFaceTB/SmolLM-360M

# General Dataloader configuration
batch_type: numel
batch_bins: 30000
num_iters_per_epoch: 10000
max_epoch: 200
num_workers: 2
drop_last_iter: true
log_interval: 1000

# Data preprocessing
codec_token_per_frame: 8
codec_token_in_use: 8 # Gradually increase this to 3, 5, 7, 9
speaker_prompt_length: 500 # 50fps, a.k.a., 10s
